=== ca0v/typescriptlab/json-schema/maplet.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "id"
  ],
  "properties": {
    "Map": {
      "$id": "#/properties/Map",
      "type": "object",
      "title": "The Map Schema",
      "required": [],
      "properties": {
        "Symbology": {
          "$id": "#/properties/Map/properties/Symbology",
          "type": "object",
          "title": "The Symbology Schema",
          "required": [
            "Symbols"
          ],
          "properties": {
            "Symbols": {
              "$id": "#/properties/Map/properties/Symbology/properties/Symbols",
              "type": "array",
              "title": "The Symbols Schema",
              "items": {
                "$id": "#/properties/Map/properties/Symbology/properties/Symbols/items",
                "type": "object",
                "title": "The Items Schema",
                "required": [
                  "id",
                  "Icons"
                ],
                "properties": {
                  "IconWidth": {
                    "type": "number"
                  },
                  "IconHeight": {
                    "type": "number"
                  },
                  "Icons": {
                    "$id": "#/properties/Map/properties/Symbology/properties/Symbols/items/properties/Icons",
                    "type": "array",
                    "title": "The Icons Schema",
                    "items": {
                      "required": [
                        "id"
                      ],
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "Width": {
                          "type": "number"
                        },
                        "Height": {
                          "type": "number"
                        }
                      }
                    }
                  },
                  "id": {
                    "$id": "#/properties/Map/properties/Symbology/properties/Symbols/items/properties/id",
                    "type": "string",
                    "title": "The Id Schema",
                    "default": "",
                    "examples": [
                      "*"
                    ],
                    "pattern": "^(.*)$"
                  },
                  "Label": {
                    "$id": "#/properties/Map/properties/Symbology/properties/Symbols/items/properties/Label",
                    "type": "string",
                    "title": "The Label Schema",
                    "default": "",
                    "examples": [
                      "<%= displayText %>"
                    ],
                    "pattern": "^(.*)$"
                  },
                  "about": {
                    "$id": "#/properties/Map/properties/Symbology/properties/Symbols/items/properties/about",
                    "type": "string",
                    "title": "The About Schema",
                    "default": "",
                    "examples": [
                      "Show displayText"
                    ],
                    "pattern": "^(.*)$"
                  }
                }
              }
            },
            "IconWidth": {
              "$id": "#/properties/Map/properties/Symbology/properties/IconWidth",
              "type": "integer",
              "title": "The Iconwidth Schema",
              "default": 0,
              "examples": [
                0
              ]
            },
            "IconHeight": {
              "$id": "#/properties/Map/properties/Symbology/properties/IconHeight",
              "type": "integer",
              "title": "The Iconheight Schema",
              "default": 0,
              "examples": [
                0
              ]
            }
          }
        },
        "Layers": {
          "$id": "#/properties/Map/properties/Layers",
          "type": "object",
          "title": "The Layers Schema",
          "required": [
            "Layers"
          ],
          "properties": {
            "Layers": {
              "$id": "#/properties/Map/properties/Layers/properties/Layers",
              "type": "array",
              "title": "The Layers Schema",
              "items": {
                "oneOf": [
                  {
                    "$id": "#/properties/Map/properties/Layers/properties/Layers/items",
                    "type": "object",
                    "title": "The Items Schema",
                    "required": [
                      "id",
                      "Layers"
                    ],
                    "properties": {
                      "Layers": {
                        "$ref": "#/properties/Map/properties/Layers"
                      }
                    }
                  },
                  {
                    "$id": "#/properties/Map/properties/Layers/properties/Layers/items",
                    "type": "object",
                    "title": "The Items Schema",
                    "required": [
                      "id",
                      "basemap",
                      "minlevel",
                      "maxlevel",
                      "disabled"
                    ],
                    "properties": {
                      "Commands": {
                        "$ref": "#/properties/Commands"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      }
    },
    "id": {
      "$id": "#/properties/id",
      "type": "string",
      "title": "The Id Schema",
      "default": "",
      "examples": [
        "rhythm-civics-address-picker"
      ],
      "pattern": "^(.*)$"
    },
    "about": {
      "$id": "#/properties/about",
      "type": "string",
      "title": "The About Schema",
      "default": "",
      "examples": [
        "User clicks the map to query for IPS addresses and parcels then selects the marker of interest"
      ],
      "pattern": "^(.*)$"
    },
    "parentId": {
      "$id": "#/properties/parentId",
      "type": "string",
      "title": "The Parentid Schema",
      "default": "",
      "examples": [
        "rhythm-civics-base,property-layers"
      ],
      "pattern": "^(.*)$"
    },
    "Commands": {
      "$id": "#/properties/Commands",
      "type": "object",
      "title": "The Commands Schema",
      "required": [
        "Commands"
      ],
      "properties": {
        "Commands": {
          "$id": "#/properties/Commands/properties/Commands",
          "type": "array",
          "title": "The Commands Schema",
          "items": {
            "$id": "#/properties/Commands/properties/Commands/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "id"
            ],
            "properties": {
              "id": {
                "$id": "#/properties/Commands/properties/Commands/items/properties/id",
                "type": "string",
                "title": "The Id Schema",
                "default": "",
                "examples": [
                  "layer-switcher"
                ],
                "pattern": "^(.*)$"
              },
              "mid": {
                "type": "string"
              },
              "about": {
                "$id": "#/properties/Commands/properties/Commands/items/properties/about",
                "type": "string",
                "title": "The About Schema",
                "default": "",
                "examples": [
                  "No layer switcher for this map"
                ],
                "pattern": "^(.*)$"
              },
              "disabled": {
                "$id": "#/properties/Commands/properties/Commands/items/properties/disabled",
                "type": "boolean",
                "title": "The Disabled Schema",
                "default": false,
                "examples": [
                  false
                ]
              }
            }
          }
        }
      }
    },
    "Controls": {
      "$id": "#/properties/Controls",
      "type": "object",
      "title": "The Controls Schema",
      "required": [
        "Controls"
      ],
      "properties": {
        "Controls": {
          "$id": "#/properties/Controls/properties/Controls",
          "type": "array",
          "title": "The Controls Schema",
          "items": {
            "$id": "#/properties/Controls/properties/Controls/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "id",
              "disabled"
            ],
            "properties": {
              "Commands": {
                "$ref": "#/properties/Commands"
              },
              "Controls": {
                "$ref": "#/properties/Controls"
              },
              "Events": {
                "$ref": "#/properties/Events"
              },
              "id": {
                "$id": "#/properties/Controls/properties/Controls/items/properties/id",
                "type": "string",
                "title": "The Id Schema",
                "default": "",
                "examples": [
                  "toolbar"
                ],
                "pattern": "^(.*)$"
              },
              "disabled": {
                "$id": "#/properties/Controls/properties/Controls/items/properties/disabled",
                "type": "boolean",
                "title": "The Disabled Schema",
                "default": false,
                "examples": [
                  false
                ]
              }
            }
          }
        }
      }
    },
    "Events": {
      "$id": "#/properties/Events",
      "type": "object",
      "title": "The Events Schema",
      "required": [
        "Events"
      ],
      "properties": {
        "Events": {
          "$id": "#/properties/Events/properties/Events",
          "type": "array",
          "title": "The Events Schema",
          "items": {
            "$id": "#/properties/Events/properties/Events/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "id"
            ],
            "properties": {
              "id": {
                "$id": "#/properties/Events/properties/Events/items/properties/id",
                "type": "string",
                "title": "The Id Schema",
                "default": "",
                "examples": [
                  "google-reverse-locator"
                ],
                "pattern": "^(.*)$"
              },
              "about": {
                "$id": "#/properties/Events/properties/Events/items/properties/about",
                "type": "string",
                "title": "The About Schema",
                "default": "",
                "examples": [
                  "shift+click will instead do an IPS address search"
                ],
                "pattern": "^(.*)$"
              },
              "disabled": {
                "$id": "#/properties/Events/properties/Events/items/properties/disabled",
                "type": "boolean",
                "title": "The Disabled Schema",
                "default": false,
                "examples": [
                  true
                ]
              }
            }
          }
        }
      }
    }
  }
}

=== ca0v/typescriptlab/json-schema/address-picker.maplet.json
{
    "$schema": "./maplet.schema.json",
    "id": "rhythm-civics-address-picker",
    "about": "User clicks the map to query for IPS addresses and parcels then selects the marker of interest",
    "parentId": "rhythm-civics-base,property-layers",
    "Map": {
        "Symbology": {
            "Symbols": [
                {
                    "Icons": [],
                    "id": "*",
                    "Label": "\u003c%= displayText %\u003e",
                    "about": "Show displayText"
                },
                {
                    "Icons": [
                        {
                            "id": "*",
                            "type": "style",
                            "style": "{\r\n    \"type\": \"mixed\",\r\n    \"image\": {\r\n        \"icon\": \"white-hole.png\",\r\n        \"anchor\": [0.5, 1.0],\r\n        \"color\": [255, 0, 0], \r\n        \"opacity\": 0.5,\r\n        \"scale\": 0.75\r\n    }\r\n}",
                            "Width": 0,
                            "Height": 0,
                            "Label": "\u003caddress\u003e\u003c%= displayText %\u003e\u003c/address\u003e"
                        }
                    ],
                    "id": "addresses",
                    "Label": "\u003c%= displayText %\u003e",
                    "about": "ips addresses"
                },
                {
                    "Icons": [
                        {
                            "id": "*",
                            "type": "style",
                            "style": "{\r\n    \"type\": \"mixed\",\r\n    \"outline\": {\r\n        \"type\": \"sls\",\r\n        \"style\": \"solid\",\r\n        \"color\": [246, 103, 197, 1],\r\n        \"width\": 1\r\n     },\r\n    \"fill\": {\r\n        \"type\": \"sfs\",\r\n        \"style\": \"solid\",\r\n        \"color\": [246, 103, 197, 0.3]\r\n    }\r\n}",
                            "Width": 0,
                            "Height": 0,
                            "Label": "\u003ch3\u003eParcel\u003c/h3\u003e",
                            "about": "Without labels"
                        },
                        {
                            "Filters": {
                                "Filters": [
                                    {
                                        "id": "zoom",
                                        "Value": "\u003e18",
                                        "about": "Only show labels when zoom exceeds 16"
                                    }
                                ]
                            },
                            "id": "labels",
                            "type": "style",
                            "style": "{\r\n    \"type\": \"mixed\",\r\n    \"text\": {\r\n        \"text\": \"\u003c%=PRCLID %\u003e\",\r\n        \"textAlign\": \"center\",\r\n        \"textBaseline\": \"top\"\r\n    },\r\n    \"outline\": {\r\n        \"type\": \"sls\",\r\n        \"style\": \"solid\",\r\n        \"color\": [246, 103, 197, 1],\r\n        \"width\": 1\r\n     },\r\n    \"fill\": {\r\n        \"type\": \"sfs\",\r\n        \"style\": \"solid\",\r\n        \"color\": [246, 103, 197, 0.3]\r\n    }\r\n}",
                            "Width": 0,
                            "Height": 0,
                            "Label": "\u003ch3\u003eParcel\u003c/h3\u003e",
                            "about": "With labels"
                        }
                    ],
                    "id": "parcels",
                    "Label": "\u003c%= PRCLNAME %\u003e",
                    "about": "ags parcels"
                }
            ],
            "IconWidth": 0,
            "IconHeight": 0
        },
        "Layers": {
            "Layers": [
                {
                    "id": "property-layer-group",
                    "minlevel": 0,
                    "disabled": false,
                    "Layers": {
                        "Layers": [
                            {
                                "id": "properties",
                                "basemap": false,
                                "minlevel": 0,
                                "maxlevel": 0,
                                "disabled": false
                            },
                            {
                                "Options": {
                                    "Values": [
                                        {
                                            "id": "layerType",
                                            "value": "rest"
                                        },
                                        {
                                            "id": "showLayers",
                                            "about": "Properties",
                                            "value": "1"
                                        },
                                        {
                                            "id": "extent",
                                            "about": "This is ignored because the LAYER already has an \"extent\" attribute",
                                            "value": "-115.3,36.16,-115.206,36.20"
                                        }
                                    ]
                                },
                                "id": "addresses",
                                "text": "Addresses",
                                "url": "//usalvwdgis1:6080/arcgis/rest/services/Vegas/MapVegas850/MapServer",
                                "type": "app/layer-factory/arcgis-tile",
                                "basemap": false,
                                "extent": "-115.3,36.16,-115.206,36.20",
                                "minlevel": 0,
                                "maxlevel": 0,
                                "disabled": true
                            }
                        ]
                    }
                },
                {
                    "Commands": {
                        "Commands": [
                            {
                                "id": "select-this-parcel",
                                "about": "Adds a command to identify this address as the one the user is interested in using",
                                "mid": "app/commands/trigger",
                                "text": "Use This Parcel",
                                "disabled": false,
                                "Options": {
                                    "Values": [
                                        {
                                            "id": "event",
                                            "about": "explicitly name the event that is fired when this command runs",
                                            "value": "civics:show-details"
                                        },
                                        {
                                            "id": "css-name",
                                            "value": "btn btn-secondary"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "Events": {
                        "Events": [
                            {
                                "name": "layer-addfeature",
                                "id": "add-feature-handler",
                                "mid": "app/commands/synthetic-add-features",
                                "disabled": false,
                                "Options": {
                                    "Values": [
                                        {
                                            "id": "event",
                                            "value": "show-info"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "Options": {
                        "Values": [
                            {
                                "id": "field-list",
                                "value": "PRCLID,OWNER,SUBNAME,CALC_ACRES,MARKAREA,TAXDIST,parcelId"
                            },
                            {
                                "id": "show-labels",
                                "value": "false"
                            },
                            {
                                "id": "field-labels",
                                "value": "Id,Owner,Sub,Acres,Area,District"
                            },
                            {
                                "id": "join-query-service",
                                "value": "property/parcels"
                            },
                            {
                                "id": "join-query-service-template",
                                "value": "{filter:{property:parcelId,operator:Equals,value:\"\u003c%= PRCLID %\u003e\"}}"
                            }
                        ]
                    },
                    "id": "parcel-features",
                    "basemap": false,
                    "minlevel": 0,
                    "maxlevel": 0,
                    "disabled": false
                },
                {
                    "Commands": {
                        "Commands": [
                            {
                                "id": "select-this-address",
                                "about": "Adds a command to identify this address as the one the user is interested in using",
                                "mid": "app/commands/trigger",
                                "text": "Use This Address",
                                "disabled": false,
                                "Options": {
                                    "Values": [
                                        {
